// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UebungsProjekt.Db;

namespace UebungsProjekt.Db.Migrations
{
    [DbContext(typeof(UebungsContext))]
    [Migration("20210211110456_CustomerMigration")]
    partial class CustomerMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("UebungApi.Addresses.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straße")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("UebungApi.Customers.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ACADEMIC_DEGREE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ADDRESS_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_ACCOUNT_MANDATE_REFERENCE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_ACCOUNT_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_ACCOUNT_OWNER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_BIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_IBAN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BANK_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CITY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("COUNTRY_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CREATED")
                        .HasColumnType("datetime2");

                    b.Property<string>("CURRENCY_CODE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_ACCOUNT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_NUMBER")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSTOMER_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAYS_FOR_PAYMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FAX")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIRST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LASTUPDATE")
                        .HasColumnType("datetime2");

                    b.Property<string>("LAST_NAME")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MOBILE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NEWSLETTER_OPTIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ORGANIZATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PAYMENT_TYPE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PHONE_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("POSITION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SALUTATION")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SECONDARY_ADDRESS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SHOW_PAYMENT_NOTICE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TAGS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TOP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAT_ID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WEBSITE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZIPCODE")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
